
name: E2E

on:
  push:    
    branches:
      - ci-test-branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
        E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        BASE_URL: https://pr-3392.mex16.dev/
        run: npx playwright test --reporter=html
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.10.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run feature tests for work orders and assets
      - name: Run feature tests
        run: npm run test tests -grep '@feature-(wo|asset)' --project=chromium --reporter=html

      # Smoke tests for PR branches - refer to package.json scripts
      - name: Run Smoke Tests
        if: github.ref != 'refs/heads/main'
        run: npm run test:smoke

      # Full regression for main - refer to package.json scripts
      - name: Run Full Tests
        if: github.ref == 'refs/heads/main'
        run: npm run test:full
       
        # Always upload raw test-results if your tests output there (e.g. trace, screenshots)
      - name: Upload Playwright test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: test-results
            path: test-results
            if-no-files-found: ignore

      # Optional: Generate HTML report (for smoke subset)
      - name: Generate HTML report
        if: always()
        run: npx playwright test tests/assets/ --workers=3 --grep "(?=.*@feature-wo)(?=.*@feature-asset)" --project=chromium --reporter=html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report             
          path: playwright-report
